// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolunteerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//	*VolunteerRequest_Hello_
	//	*VolunteerRequest_FinishWork
	//	*VolunteerRequest_JobError
	Req isVolunteerRequest_Req `protobuf_oneof:"req"`
}

func (x *VolunteerRequest) Reset() {
	*x = VolunteerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolunteerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerRequest) ProtoMessage() {}

func (x *VolunteerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerRequest.ProtoReflect.Descriptor instead.
func (*VolunteerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (m *VolunteerRequest) GetReq() isVolunteerRequest_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *VolunteerRequest) GetHello() *VolunteerRequest_Hello {
	if x, ok := x.GetReq().(*VolunteerRequest_Hello_); ok {
		return x.Hello
	}
	return nil
}

func (x *VolunteerRequest) GetFinishWork() *WorkResponse {
	if x, ok := x.GetReq().(*VolunteerRequest_FinishWork); ok {
		return x.FinishWork
	}
	return nil
}

func (x *VolunteerRequest) GetJobError() string {
	if x, ok := x.GetReq().(*VolunteerRequest_JobError); ok {
		return x.JobError
	}
	return ""
}

type isVolunteerRequest_Req interface {
	isVolunteerRequest_Req()
}

type VolunteerRequest_Hello_ struct {
	Hello *VolunteerRequest_Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type VolunteerRequest_FinishWork struct {
	FinishWork *WorkResponse `protobuf:"bytes,2,opt,name=finish_work,json=finishWork,proto3,oneof"`
}

type VolunteerRequest_JobError struct {
	JobError string `protobuf:"bytes,3,opt,name=job_error,json=jobError,proto3,oneof"`
}

func (*VolunteerRequest_Hello_) isVolunteerRequest_Req() {}

func (*VolunteerRequest_FinishWork) isVolunteerRequest_Req() {}

func (*VolunteerRequest_JobError) isVolunteerRequest_Req() {}

type VolunteerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Resp:
	//	*VolunteerResponse_StartJob
	//	*VolunteerResponse_StartWork
	//	*VolunteerResponse_EndJob_
	Resp isVolunteerResponse_Resp `protobuf_oneof:"resp"`
}

func (x *VolunteerResponse) Reset() {
	*x = VolunteerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolunteerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerResponse) ProtoMessage() {}

func (x *VolunteerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerResponse.ProtoReflect.Descriptor instead.
func (*VolunteerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (m *VolunteerResponse) GetResp() isVolunteerResponse_Resp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (x *VolunteerResponse) GetStartJob() *Job {
	if x, ok := x.GetResp().(*VolunteerResponse_StartJob); ok {
		return x.StartJob
	}
	return nil
}

func (x *VolunteerResponse) GetStartWork() *WorkRequest {
	if x, ok := x.GetResp().(*VolunteerResponse_StartWork); ok {
		return x.StartWork
	}
	return nil
}

func (x *VolunteerResponse) GetEndJob() *VolunteerResponse_EndJob {
	if x, ok := x.GetResp().(*VolunteerResponse_EndJob_); ok {
		return x.EndJob
	}
	return nil
}

type isVolunteerResponse_Resp interface {
	isVolunteerResponse_Resp()
}

type VolunteerResponse_StartJob struct {
	StartJob *Job `protobuf:"bytes,1,opt,name=start_job,json=startJob,proto3,oneof"`
}

type VolunteerResponse_StartWork struct {
	StartWork *WorkRequest `protobuf:"bytes,2,opt,name=start_work,json=startWork,proto3,oneof"`
}

type VolunteerResponse_EndJob_ struct {
	EndJob *VolunteerResponse_EndJob `protobuf:"bytes,3,opt,name=end_job,json=endJob,proto3,oneof"`
}

func (*VolunteerResponse_StartJob) isVolunteerResponse_Resp() {}

func (*VolunteerResponse_StartWork) isVolunteerResponse_Resp() {}

func (*VolunteerResponse_EndJob_) isVolunteerResponse_Resp() {}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectName   string `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Wasm          []byte `protobuf:"bytes,2,opt,name=wasm,proto3" json:"wasm,omitempty"`
	NumWork       int32  `protobuf:"varint,3,opt,name=num_work,json=numWork,proto3" json:"num_work,omitempty"`
	MinRamMb      int32  `protobuf:"varint,4,opt,name=min_ram_mb,json=minRamMb,proto3" json:"min_ram_mb,omitempty"`
	OnePerMachine bool   `protobuf:"varint,5,opt,name=one_per_machine,json=onePerMachine,proto3" json:"one_per_machine,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *Job) GetWasm() []byte {
	if x != nil {
		return x.Wasm
	}
	return nil
}

func (x *Job) GetNumWork() int32 {
	if x != nil {
		return x.NumWork
	}
	return 0
}

func (x *Job) GetMinRamMb() int32 {
	if x != nil {
		return x.MinRamMb
	}
	return 0
}

func (x *Job) GetOnePerMachine() bool {
	if x != nil {
		return x.OnePerMachine
	}
	return false
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//	*SubmitJobRequest_Job
	//	*SubmitJobRequest_AddWork
	Req isSubmitJobRequest_Req `protobuf_oneof:"req"`
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (m *SubmitJobRequest) GetReq() isSubmitJobRequest_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *SubmitJobRequest) GetJob() *Job {
	if x, ok := x.GetReq().(*SubmitJobRequest_Job); ok {
		return x.Job
	}
	return nil
}

func (x *SubmitJobRequest) GetAddWork() *WorkRequest {
	if x, ok := x.GetReq().(*SubmitJobRequest_AddWork); ok {
		return x.AddWork
	}
	return nil
}

type isSubmitJobRequest_Req interface {
	isSubmitJobRequest_Req()
}

type SubmitJobRequest_Job struct {
	Job *Job `protobuf:"bytes,1,opt,name=job,proto3,oneof"`
}

type SubmitJobRequest_AddWork struct {
	AddWork *WorkRequest `protobuf:"bytes,2,opt,name=add_work,json=addWork,proto3,oneof"`
}

func (*SubmitJobRequest_Job) isSubmitJobRequest_Req() {}

func (*SubmitJobRequest_AddWork) isSubmitJobRequest_Req() {}

type SubmitJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Resp:
	//	*SubmitJobResponse_CompletedWork
	Resp isSubmitJobResponse_Resp `protobuf_oneof:"resp"`
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (m *SubmitJobResponse) GetResp() isSubmitJobResponse_Resp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (x *SubmitJobResponse) GetCompletedWork() *WorkResponse {
	if x, ok := x.GetResp().(*SubmitJobResponse_CompletedWork); ok {
		return x.CompletedWork
	}
	return nil
}

type isSubmitJobResponse_Resp interface {
	isSubmitJobResponse_Resp()
}

type SubmitJobResponse_CompletedWork struct {
	CompletedWork *WorkResponse `protobuf:"bytes,2,opt,name=completed_work,json=completedWork,proto3,oneof"`
}

func (*SubmitJobResponse_CompletedWork) isSubmitJobResponse_Resp() {}

type WorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *WorkRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WorkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Result       []byte `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *WorkResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WorkResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type VolunteerRequest_Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname         string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Cpus             int32  `protobuf:"varint,2,opt,name=cpus,proto3" json:"cpus,omitempty"`
	RamMbAllocatable int32  `protobuf:"varint,3,opt,name=ram_mb_allocatable,json=ramMbAllocatable,proto3" json:"ram_mb_allocatable,omitempty"`
}

func (x *VolunteerRequest_Hello) Reset() {
	*x = VolunteerRequest_Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolunteerRequest_Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerRequest_Hello) ProtoMessage() {}

func (x *VolunteerRequest_Hello) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerRequest_Hello.ProtoReflect.Descriptor instead.
func (*VolunteerRequest_Hello) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *VolunteerRequest_Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *VolunteerRequest_Hello) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *VolunteerRequest_Hello) GetRamMbAllocatable() int32 {
	if x != nil {
		return x.RamMbAllocatable
	}
	return 0
}

type VolunteerResponse_EndJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VolunteerResponse_EndJob) Reset() {
	*x = VolunteerResponse_EndJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolunteerResponse_EndJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolunteerResponse_EndJob) ProtoMessage() {}

func (x *VolunteerResponse_EndJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolunteerResponse_EndJob.ProtoReflect.Descriptor instead.
func (*VolunteerResponse_EndJob) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 0}
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x22, 0xb6, 0x02, 0x0a, 0x10, 0x56, 0x6f, 0x6c, 0x75, 0x6e,
	0x74, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x49, 0x0a, 0x05, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6e, 0x74, 0x65, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52,
	0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x4a, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x57, 0x6f,
	0x72, 0x6b, 0x12, 0x1d, 0x0a, 0x09, 0x6a, 0x6f, 0x62, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x6a, 0x6f, 0x62, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x1a, 0x65, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x70, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x70, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x61,
	0x6d, 0x5f, 0x6d, 0x62, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x72, 0x61, 0x6d, 0x4d, 0x62, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x22,
	0xfd, 0x01, 0x0a, 0x11, 0x56, 0x6f, 0x6c, 0x75, 0x6e, 0x74, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6a,
	0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x77, 0x61, 0x73, 0x6d, 0x2e, 0x4a, 0x6f, 0x62, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x4a, 0x6f, 0x62, 0x12, 0x47, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x77, 0x6f,
	0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x77, 0x61, 0x73, 0x6d, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x4e, 0x0a,
	0x07, 0x65, 0x6e, 0x64, 0x5f, 0x6a, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c,
	0x65, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6e,
	0x74, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x64,
	0x4a, 0x6f, 0x62, 0x48, 0x00, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x1a, 0x08, 0x0a,
	0x06, 0x45, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x42, 0x06, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22,
	0x9d, 0x01, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61,
	0x73, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x77, 0x61, 0x73, 0x6d, 0x12, 0x19,
	0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x6e, 0x75, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x1c, 0x0a, 0x0a, 0x6d, 0x69, 0x6e,
	0x5f, 0x72, 0x61, 0x6d, 0x5f, 0x6d, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d,
	0x69, 0x6e, 0x52, 0x61, 0x6d, 0x4d, 0x62, 0x12, 0x26, 0x0a, 0x0f, 0x6f, 0x6e, 0x65, 0x5f, 0x70,
	0x65, 0x72, 0x5f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x6f, 0x6e, 0x65, 0x50, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x22,
	0x92, 0x01, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a,
	0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x4a, 0x6f,
	0x62, 0x48, 0x00, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x43, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f,
	0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x42, 0x05, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x22, 0x6d, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0e, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a,
	0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x72,
	0x65, 0x73, 0x70, 0x22, 0x31, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5b, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0xe9, 0x01, 0x0a, 0x0b, 0x4b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x6c, 0x0a, 0x09, 0x56, 0x6f, 0x6c, 0x75, 0x6e, 0x74, 0x65, 0x65, 0x72,
	0x12, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69,
	0x6c, 0x6c, 0x65, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x56, 0x6f, 0x6c,
	0x75, 0x6e, 0x74, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c, 0x65,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6e, 0x74,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x6c, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x2b,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c,
	0x65, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x4a, 0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x69,
	0x6c, 0x6c, 0x65, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_goTypes = []interface{}{
	(*VolunteerRequest)(nil),         // 0: com.github.Jille.distwasm.VolunteerRequest
	(*VolunteerResponse)(nil),        // 1: com.github.Jille.distwasm.VolunteerResponse
	(*Job)(nil),                      // 2: com.github.Jille.distwasm.Job
	(*SubmitJobRequest)(nil),         // 3: com.github.Jille.distwasm.SubmitJobRequest
	(*SubmitJobResponse)(nil),        // 4: com.github.Jille.distwasm.SubmitJobResponse
	(*WorkRequest)(nil),              // 5: com.github.Jille.distwasm.WorkRequest
	(*WorkResponse)(nil),             // 6: com.github.Jille.distwasm.WorkResponse
	(*VolunteerRequest_Hello)(nil),   // 7: com.github.Jille.distwasm.VolunteerRequest.Hello
	(*VolunteerResponse_EndJob)(nil), // 8: com.github.Jille.distwasm.VolunteerResponse.EndJob
}
var file_api_proto_depIdxs = []int32{
	7,  // 0: com.github.Jille.distwasm.VolunteerRequest.hello:type_name -> com.github.Jille.distwasm.VolunteerRequest.Hello
	6,  // 1: com.github.Jille.distwasm.VolunteerRequest.finish_work:type_name -> com.github.Jille.distwasm.WorkResponse
	2,  // 2: com.github.Jille.distwasm.VolunteerResponse.start_job:type_name -> com.github.Jille.distwasm.Job
	5,  // 3: com.github.Jille.distwasm.VolunteerResponse.start_work:type_name -> com.github.Jille.distwasm.WorkRequest
	8,  // 4: com.github.Jille.distwasm.VolunteerResponse.end_job:type_name -> com.github.Jille.distwasm.VolunteerResponse.EndJob
	2,  // 5: com.github.Jille.distwasm.SubmitJobRequest.job:type_name -> com.github.Jille.distwasm.Job
	5,  // 6: com.github.Jille.distwasm.SubmitJobRequest.add_work:type_name -> com.github.Jille.distwasm.WorkRequest
	6,  // 7: com.github.Jille.distwasm.SubmitJobResponse.completed_work:type_name -> com.github.Jille.distwasm.WorkResponse
	0,  // 8: com.github.Jille.distwasm.KingService.Volunteer:input_type -> com.github.Jille.distwasm.VolunteerRequest
	3,  // 9: com.github.Jille.distwasm.KingService.SubmitJob:input_type -> com.github.Jille.distwasm.SubmitJobRequest
	1,  // 10: com.github.Jille.distwasm.KingService.Volunteer:output_type -> com.github.Jille.distwasm.VolunteerResponse
	4,  // 11: com.github.Jille.distwasm.KingService.SubmitJob:output_type -> com.github.Jille.distwasm.SubmitJobResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolunteerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolunteerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolunteerRequest_Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolunteerResponse_EndJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*VolunteerRequest_Hello_)(nil),
		(*VolunteerRequest_FinishWork)(nil),
		(*VolunteerRequest_JobError)(nil),
	}
	file_api_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*VolunteerResponse_StartJob)(nil),
		(*VolunteerResponse_StartWork)(nil),
		(*VolunteerResponse_EndJob_)(nil),
	}
	file_api_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*SubmitJobRequest_Job)(nil),
		(*SubmitJobRequest_AddWork)(nil),
	}
	file_api_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*SubmitJobResponse_CompletedWork)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
